language: php

sudo: false

php:
  - 5.6

git:
  submodules: false
  depth: 10

env:
  global:
    - S3_BUCKET="acn-bootcamp-internal"
    - AWS_REGION="us-east-1"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --optimize-autoloader --prefer-source --no-interaction --dev
  - npm install

script:
  - ./node_modules/.bin/gulp

after_success:
  - export REPO_NAME=`basename $TRAVIS_REPO_SLUG`
  - rsync -a --exclude .git --exclude tests/ --exclude node_modules/ . /tmp/build-$TRAVIS_BUILD_NUMBER
  - mkdir -p /tmp/build-tar/
  - cd /tmp/build-$TRAVIS_BUILD_NUMBER/
  - tar -zcvf /tmp/build-tar/$REPO_NAME-$TRAVIS_BUILD_NUMBER.tar.gz .
  - cd -
  - ls -la /tmp/build-$TRAVIS_BUILD_NUMBER/
  - ls -la /tmp/build-tar/

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  local-dir: /tmp/build-tar
  upload-dir: builds/$REPO_NAME
  acl: authenticated_read
  on:
    branch: master

after_deploy:
    - php build/deploy.php
