version: 0.0
os: linux
files:
  - source: .
    destination: /http/ui-svc
hooks:
  BeforeInstall:
    - location: hooks/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: hooks/after_install.sh
      runas: root
      timeout: 300
